variable "env" {}
variable "subnets" {}
variable "name" {}
variable "instance_type" {}
variable "min_size" {}
variable "max_size" {}
variable "vpc_id" {}
variable "BASTION_NODE" {}
variable "app_port_no" {}
variable "vpc_cidr" {}
variable "PROMETHEUS_NODE" {}